### ISSUE TITLE
GPM not up-to-date

### ISSUE THREAD

**Issue by N-Parsons** [OleVik/grav-plugin-swiper#1]
Hi @OleVik,

The current version of this plugin available via GPM is `v1.0.0`. This is due to an inconsistency in your release version numbers on GitHub: the first release is `v1.0.0`, while later releases are `1.0.1` and `1.0.2` (note the absence of the `v`). The GPM requires consistency in version formatting, so you need to re-release this plugin as `v1.0.2` in order for the GPM to get updated.

**Comment by OleVik** [comment]
No, this is due to an inconsistency in the GPM which misinterprets the prefix, and there is an [open issue regarding it on the Core repo](https://github.com/getgrav/grav/issues/2827).

**Comment by N-Parsons** [comment]
As far as I'm aware, it's not that GPM is misinterpreting the prefix, but rather it is attempting to understand the later version numbers based on the initial format, which fails when the format doesn't match. I appreciate that it's a non-obvious behaviour of the GPM, and it's a mistake that many people have made and continue to make, but GPM is being consistent (albeit not robust).

Users aren't going to be able to get the most recent version of this plugin from the GPM until the either the behaviour of the GPM is changed, or you create a new release with the `v` prefix.

As a side-note, while using a `v` prefix is not Canonical SemVer, it is valid for versioning in the GPM, and many plugins (including all of my own) use the prefix.

From https://semver.org/#is-v123-a-semantic-version:
> **Is “v1.2.3” a semantic version?**
> No, “v1.2.3” is not a semantic version. However, prefixing a semantic version with a “v” is a common way (in English) to indicate it is a version number. Abbreviating “version” as “v” is often seen with version control. Example: git tag v1.2.3 -m "Release version 1.2.3", in which case “v1.2.3” is a tag name and the semantic version is “1.2.3”.

**Comment by OleVik** [comment]
Indeed, as do most of mine, but I am moving away from including the prefix - and the upcoming version of the GPM should resolve this. I am, however, unwilling to maintain the prevalence of the `v`-prefix just for GPM-compatibility. I want to move towards publishing all plugins on Packagist, and so Composer-compatibility - which relies on proper SemVer - is paramount.

As noted in the referenced issue, `1.0.2` should take precedence over `v1.0.0`, the `v`-prefix should be discarded when comparing the versions.
